config/routes.rb
Template::Application.routes.draw do 

  # get '/delayed_job' => DelayedJobWeb, anchor: false

  namespace :api do
    namespace :v1 do
      post "authentications" => "authentications#create"
      post "nao_conformidades" => "nao_conformidades#index"
      post "nao_conformidade" => "nao_conformidades#show"
      post "finalizar" => "nao_conformidades#finalizar"
      post "escalonar" => "nao_conformidades#escalonar"
      post "gcm" => "gcm#show"
    end
  end

  ### PASSOS DA AUDITORIA
  match 'primeiro_passo' => 'home#primeiro_passo'
  match 'pesquisa_ordem_servico' => 'home#pesquisa_ordem_servico'
  match 'segundo_passo' => 'home#segundo_passo'
  match 'iniciar_auditoria' => 'home#iniciar_auditoria'
  match 'ultimo_passo' => 'home#ultimo_passo'

  namespace :administracao do
    devise_for :usuarios, controllers: { sessions: 'administracao/sessions',
                                         registrations: 'administracao/registrations' }
    root to: 'home#index'
    resources :entidades do 
      member do 
        get :change_status
      end
    end

    resources :administradores do 
       member do 
        get :change_status
      end
    end
  end

  match ':entidade_slug' => 'home#index', as: :entidade, module: :modulo_entidades
  scope ':entidade_slug', as: :entidade, module: :modulo_entidades do
    match 'acessar' => 'home#index'
    namespace :administracao do

      resources :unidades do
        member do
          get :change_status
        end
        collection do 
          get  :escolher_unidade
          post :acessando_unidade
          get  :sair_unidade
        end
      end

      resources :perfils do
        member do
          get :change_status
        end
      end

      resources :configuracoes

      root to: 'home#index'
    end

    resources :nao_conformidades

    resources :checklists do
      member do
        get :change_status
      end
      
      collection do 
        post :edit_questao_ajax
        post :edit_categoria_ajax
        post :nova_acao 
        post :altera_situacao_categoria
        post :altera_situacao_questao
        post :detalhe_questao
      end
      resources :questoes do 
        collection do 
          post :nova_categoria_questao
          post :nova_subcategoria_questao
          post :carrega_subcategoria
          post :nova_questao
          post :carrega_form_questao
          post :atualiza_categoria
          post :atualiza_item_verificacao
          post :cria_acao
          post :carrega_alternativa
          get :inserir_imagem
          post :upload_imagem
        end
      end
    end


    resources :auditorias do
      collection do
        get  :iniciar_pesquisa
        post :retorna_clientes
      end
    end


    resources :clientes do
      collection do
        post :autocomplete_by_nf
      end
    end


    resources :usuarios do
      member do
        get :change_status
      end
    end

    resources :relatorios do
      collection do
        get :pesquisas_respondidas
        get :pesquisas_detalhadas
        get :dashboards
        get :relatorio_ordem_servicos
      end
    end

    root to: 'home#index'
  end
  
  root to: 'home#index'
end

app/controllers/administracao/administradores_controller.rb
#encoding: UTF-8

class Administracao::AdministradoresController < ApplicationController
	
	before_filter :valid_payment
	before_filter :verifica_se_o_usuario_eh_administrador_do_sistema


	def index
		params[:pesquisa] ||= {}
		if params[:pesquisa][:texto].present?
		 	@administradores = Usuario.pesquisa_administradores(params[:pesquisa])
		 														.page(params[:page]).per(15)
		else
			@administradores = Usuario.where(tipo: Usuario::ADMINISTRADOR_GERAL_DO_SISTEMA)
																.order(:nome).page(params[:page]).per(15)
		end
	end

	def show
		@administrador = Usuario.find params[:id]
	end

	def new
		@administrador = Administrador.new
	end

	def create
		@administrador = Administrador.new(params[:administrador])
		@administrador.tipo = Usuario::ADMINISTRADOR_GERAL_DO_SISTEMA
		if @administrador.save
			redirect_to [:administracao, @administrador], notice: 'Usuário criado com sucesso!'
		else
			render :new
		end
	end

	def edit
		@administrador = Administrador.find(params[:id])
	end

	def update
		@administrador = Administrador.find(params[:id])
		if @administrador.update_attributes(params[:administrador])
			redirect_to [:administracao, @administrador], notice: 'Usuário atualizado com sucesso!'
		else
			render :edit
		end
	end

	def change_status
		@administrador = Usuario.find(params[:id])
		if @administrador.situacao == Usuario::ATIVO
			@administrador.situacao = Usuario::INATIVO
		else
			@administrador.situacao = Usuario::ATIVO
		end
		if @administrador.save
			redirect_to [:administracao, :administradores], notice: 'Situação alterada com sucesso!'
		else
			redirect_to [:administracao, :administradores], notice: 'Não foi possível alterar a situação do registro!'
		end
	end

end

app/controllers/administracao/entidades_controller.rb
#encoding: UTF-8

class Administracao::EntidadesController < ApplicationController

  before_filter :valid_payment
	before_filter :verifica_se_o_usuario_eh_administrador_do_sistema


	def index
		params[:pesquisa] ||= {}
		unless params[:pesquisa][:texto].blank?
			@entidades = Entidade.pesquisa(params[:pesquisa]).page(params[:page]).per(15)
		else
			@entidades = Entidade.order(:nome).page(params[:page]).per(15)
		end
	end

	def show
		@entidade = Entidade.find params[:id]
		@usuario = @entidade.administrador_entidade
	end

	def new
		@entidade = Entidade.new
		@usuario = @entidade.usuarios.build
	end

	def create
		@entidade = Entidade.new params[:entidade]
		@entidade.usuarios.first.tipo = Usuario::ADMINISTRADOR_ENTIDADE
		if @entidade.save
			redirect_to [:administracao, @entidade], notice: 'Entidade criada com sucesso!'
		else
			render :new
		end
	end

	def change_status
		@entidade = Entidade.find params[:id]
		if @entidade.situacao == Entidade::ATIVO
			@entidade.situacao = Entidade::INATIVO
		else
			@entidade.situacao = Entidade::ATIVO
		end
		if @entidade.save
			redirect_to [:administracao,:entidades], notice: 'Situação alterada com sucesso!'
		else
			redirect_to [:administracao,:entidades], notice: 'Não foi possível alterar a situação do registro!'
		end
	end

	def edit
		@entidade = Entidade.find params[:id]
	end

	def update
		@entidade = Entidade.find params[:id]
		if @entidade.update_attributes(params[:entidade])
			redirect_to [:administracao,@entidade], notice: 'Entidade atualizada com sucesso!'
		else
			render :edit
		end
	end
	
end

app/controllers/administracao/home_controller.rb
class Administracao::HomeController < ApplicationController

	def index
	end
	
end

app/controllers/administracao/passwords_controller.rb
class Administracao::PasswordsController < Devise::PasswordsController

	before_filter :valid_payment

end

app/controllers/administracao/registrations_controller.rb
class Administracao::RegistrationsController < Devise::RegistrationsController

	before_filter :valid_payment
	
end

app/controllers/administracao/sessions_controller.rb
class Administracao::SessionsController < ::Devise::SessionsController
	
	before_filter :valid_payment
	
  # the rest is inherited, so it should work

end

app/controllers/modulo_entidades/administracao/configuracoes_controller.rb
#encoding: UTF-8

class ModuloEntidades::Administracao::ConfiguracoesController < ApplicationController

	before_filter :valid_payment
	before_filter :verifica_se_o_usuario_eh_administrador_de_entidade

	def edit
		@configuracao = Configuracao.last
	end

	def update
		@configuracao = Configuracao.find(params[:id])
		if @configuracao.update_attributes(params[:configuracao])
			redirect_to [:edit, :entidade, :administracao, @configuracao], notice: 'Configuração atualizada com sucesso!'
		else
			render action: :edit
		end
	end

end

app/controllers/modulo_entidades/administracao/home_controller.rb
#encoding: UTF-8

class ModuloEntidades::Administracao::HomeController < ApplicationController

	before_filter :valid_payment
	before_filter :verifica_se_o_usuario_eh_administrador_de_entidade


	def index
	end
	
end

app/controllers/modulo_entidades/administracao/perfils_controller.rb
#encoding: UTF-8

class ModuloEntidades::Administracao::PerfilsController < ApplicationController

	before_filter :valid_payment
	before_filter :verifica_se_o_usuario_eh_administrador_de_entidade


	def index
		params[:pesquisa] ||= {}
		@perfils = Perfil.pesquisa(current_entidade.id, params[:pesquisa]).page(params[:page]).per(15)
    respond_to do |format|
      format.html
      format.json { render json: @perfils }
    end
	end

	def show
		@perfil = Perfil.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @perfil }
    end
	end

	def new
		@perfil = Perfil.new
	end

	def create
		@perfil = Perfil.new(params[:perfil])
		@perfil.entidade = current_entidade
		if @perfil.save
			redirect_to [:entidade, :administracao, @perfil], notice: 'Registro cadastrado com sucesso!'
		else
			render :new
		end
	end

	def edit
		@perfil = Perfil.find(params[:id])
	end

	def update
		@perfil = Perfil.find(params[:id])
		if @perfil.update_attributes(params[:perfil]) && params[:perfil].has_key?(:permissoes)
			redirect_to [:entidade, :administracao, @perfil], notice: 'Registro atualizado com sucesso!'
		else
			flash[:error] = 'Permissões não pode ficar em branco'
			render :edit
		end
	end

  def change_status
    @perfil = Perfil.find(params[:id])
    @perfil.change_status
    respond_to do |format|
      format.html do
        redirect_to [:entidade, :administracao, :perfils], notice: 'Situação alterada com sucesso!'
      end
      format.json do
        head :no_content
      end
    end
  end

end

app/controllers/modulo_entidades/administracao/unidades_controller.rb
#encoding: UTF-8

class ModuloEntidades::Administracao::UnidadesController < ApplicationController

	before_filter :valid_payment
	before_filter :verifica_se_o_usuario_eh_administrador_de_entidade


	def index
		params[:pesquisa] ||= {}
		@unidades = Unidade.pesquisa(current_entidade.id, params[:pesquisa]).page(params[:page]).per(15)
	end

	def show
		@unidade = Unidade.find(params[:id])
	end

	def new
		@unidade = Unidade.new
	end

	def create
		@unidade = Unidade.new(params[:unidade])
		@unidade.entidade = current_entidade
		if @unidade.save
			redirect_to [:entidade, :administracao, @unidade], notice: 'Unidade criada com sucesso!'
		else
			render :new
		end
	end

	def edit
		@unidade = Unidade.find(params[:id])
	end

	def update
		@unidade = Unidade.find(params[:id])
		if @unidade.update_attributes(params[:unidade])
			redirect_to [:entidade, :administracao, @unidade], notice: 'Unidade atualizada com sucesso!'
		else
			render :edit
		end
	end

  def change_status
    @unidade = Unidade.find(params[:id])
    @unidade.change_status
    respond_to do |format|
      format.html do
        redirect_to [:entidade, :administracao, :unidades], notice: 'Status alterado com sucesso!'
      end
      format.json do
        head :no_content
      end
    end
  end

	def escolher_unidade
	end

	def sair_unidade
		session[:unidade] = nil
		redirect_to [:escolher_unidade, :entidade, :administracao, :unidades]
	end

	def acessando_unidade
		session[:unidade] = Unidade.find_by_id(params[:unidade_id])
		if session[:unidade].blank?
			flash[:error] = 'Erro! Você deve selecionar uma unidade!'
			redirect_to root_path
		else
			redirect_to [:entidade, :root]
		end
	end

end

app/helpers/administracao/administracao_entidades/unidades_helper.rb
module Administracao::AdministracaoEntidades::UnidadesHelper
end

app/helpers/modulo_entidades/administracao/configuracoes_helper.rb
module ModuloEntidades::Administracao::ConfiguracoesHelper
end

app/helpers/modulo_entidades/administracao/perfils_helper.rb
module ModuloEntidades::Administracao::PerfilsHelper
end

app/helpers/modulo_entidades/administracao/unidades_helper.rb
module ModuloEntidades::Administracao::UnidadesHelper
end

app/helpers/modulo_entidades/administracao/usuarios_helper.rb
module ModuloEntidades::Administracao::UsuariosHelper
end

app/views/administracao/administradores/_form.html.erb
<%= form_for @administrador,:url=>{:action=> @administrador.new_record? ? "create" : "update"}, html: { class: 'form-horizontal', :method=> @administrador.new_record? ? "post": "put" } do |f| %>
  
  <%= error_messages(@administrador) %>

  <div class="field control-group">
    <%= f.label :nome, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :nome, class: 'input-xlarge', maxlength: 255 %>
    </div>
  </div>

  <div class="field control-group">
    <%= f.label :email, class: 'control-label' %>
    <div class="controls">
      <%= f.email_field :email, class: 'input-xlarge', maxlength: 255 %>
    </div>
  </div>

    <div class="field control-group">
    <%= f.label :login, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :login, class: 'input-xlarge', maxlength: 255 %>
    </div>
  </div>

    <div class="field control-group">
    <%= f.label :password, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, class: 'input-xlarge', maxlength: 255 %>
    </div>
  </div>

    <div class="field control-group">
    <%= f.label :password_confirmation, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, class: 'input-xlarge', maxlength: 255 %>
    </div>
  </div>

  <div class="actions form-actions">
    <%= f.submit 'Salvar', class: 'btn btn-inverse', data: { disable_with: 'Salvando...' } %>
    
      <%= link_to 'Cancelar', [:administracao, :administradores], class: 'btn' %>
    
  </div>
<% end %>

app/views/administracao/administradores/edit.html.erb
<div class="titulo-pagina">
  Alterar Usuário Administrador »
</div>
<br />
<%= render 'form' %>

app/views/administracao/administradores/index.html.erb
<div class="titulo-pagina">
  Administradores do Sistema »
</div>
<br />

<%= form_tag [:administracao, :administradores], method: :get, class: 'form-inline' do %>
  <div class="input-append">
    <%= text_field_tag 'pesquisa[texto]', params[:pesquisa][:texto], class: 'input-xxlarge', placeholder: 'insira o nome ou login do usuário aqui' %>
    <%= button_tag 'Pesquisar', class: 'btn', data: { disable_with: 'Pesquisando...' } %>
  </div>
<% end %>

<%if @administradores.any?%>
	<table class="table table-striped table-condensed">
		<thead>
			<tr>
				<th>Nome</th>
				<th>Email</th>
				<th>Login</th>
				<th>Situação</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>
			<%@administradores.each do |objeto|%>
				<tr>
					<td><%=objeto.nome%></td>
					<td><%=objeto.email%></td>
					<td><%=objeto.login%></td>
					<td><%=objeto.situacao_verbose%></td>
					<td>
						<%=link_to 'Editar', edit_administracao_administrador_path(objeto)%>
					</td>
					<td>
						<%=link_to 'Detalhes', administracao_administrador_path(objeto)%>
					</td>
					<td>
						<%=link_to 'Alterar Situação', change_status_administracao_administrador_path(objeto),:confirm=>"Deseja alterar a situação deste registro?"%>
					</td>
				</tr>
			<%end%>
		</tbody>

	</table>
<%else%>
	<strong>Sem registros para exibir!</strong>
<%end%>

<%= paginate @administradores %>

<div class="actions form-actions well">
	<%=link_to 'Novo',new_administracao_administrador_path, class: 'btn btn-inverse' %>
</div>

app/views/administracao/administradores/new.html.erb
<div class="titulo-pagina">
  Novo Usuário Administrador »
</div>
<br />
<%= render 'form' %>

app/views/administracao/administradores/show.html.erb
<div class="titulo-pagina">
  Detalhes - Usuário »
</div>

<dl class="dl-horizontal">
  <%= show_unless_blank('Tipo', @administrador.tipo_verbose) %>
  <%= show_unless_blank('Nome', @administrador.nome) %>
  <%= show_unless_blank('Login', @administrador.login) %>
  <%= show_unless_blank('Email', @administrador.email) %>
  <%= show_unless_blank('Situação', @administrador.situacao_verbose) %>
</dl>

<div class="actions form-actions well">
  <%= link_to 'Alterar', edit_administracao_administrador_path(@administrador), class: 'btn btn-inverse' %>
  <%= link_to 'Voltar', administracao_administradores_path, class: 'btn' %>
</div>