config/routes.rb
Template::Application.routes.draw do 

  # get '/delayed_job' => DelayedJobWeb, anchor: false

  namespace :api do
    namespace :v1 do
      post "authentications" => "authentications#create"
      post "nao_conformidades" => "nao_conformidades#index"
      post "nao_conformidade" => "nao_conformidades#show"
      post "finalizar" => "nao_conformidades#finalizar"
      post "escalonar" => "nao_conformidades#escalonar"
      post "gcm" => "gcm#show"
    end
  end

  ### PASSOS DA AUDITORIA
  match 'primeiro_passo' => 'home#primeiro_passo'
  match 'pesquisa_ordem_servico' => 'home#pesquisa_ordem_servico'
  match 'segundo_passo' => 'home#segundo_passo'
  match 'iniciar_auditoria' => 'home#iniciar_auditoria'
  match 'ultimo_passo' => 'home#ultimo_passo'

  namespace :administracao do
    devise_for :usuarios, controllers: { sessions: 'administracao/sessions',
                                         registrations: 'administracao/registrations' }
    root to: 'home#index'
    resources :entidades do 
      member do 
        get :change_status
      end
    end

    resources :administradores do 
       member do 
        get :change_status
      end
    end
  end

  match ':entidade_slug' => 'home#index', as: :entidade, module: :modulo_entidades
  scope ':entidade_slug', as: :entidade, module: :modulo_entidades do
    match 'acessar' => 'home#index'
    namespace :administracao do

      resources :unidades do
        member do
          get :change_status
        end
        collection do 
          get  :escolher_unidade
          post :acessando_unidade
          get  :sair_unidade
        end
      end

      resources :perfils do
        member do
          get :change_status
        end
      end

      resources :configuracoes

      root to: 'home#index'
    end

    resources :nao_conformidades

    resources :checklists do
      member do
        get :change_status
      end
      
      collection do 
        post :edit_questao_ajax
        post :edit_categoria_ajax
        post :nova_acao 
        post :altera_situacao_categoria
        post :altera_situacao_questao
        post :detalhe_questao
      end
      resources :questoes do 
        collection do 
          post :nova_categoria_questao
          post :nova_subcategoria_questao
          post :carrega_subcategoria
          post :nova_questao
          post :carrega_form_questao
          post :atualiza_categoria
          post :atualiza_item_verificacao
          post :cria_acao
          post :carrega_alternativa
          get :inserir_imagem
          post :upload_imagem
        end
      end
    end


    resources :auditorias do
      collection do
        get  :iniciar_pesquisa
        post :retorna_clientes
      end
    end


    resources :clientes do
      collection do
        post :autocomplete_by_nf
      end
    end


    resources :usuarios do
      member do
        get :change_status
      end
    end

    resources :relatorios do
      collection do
        get :pesquisas_respondidas
        get :pesquisas_detalhadas
        get :dashboards
        get :relatorio_ordem_servicos
      end
    end

    root to: 'home#index'
  end
  
  root to: 'home#index'
end

app/controllers/administracao/home_controller.rb
class Administracao::HomeController < ApplicationController

	def index
	end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_filter :valid_payment
	

	def index
		# @retorno = Auditoria.retorna_auditoria_para_ser_respondida
		render layout: 'auditoria_inicial' if current_unidade.blank?
	end

  def primeiro_passo
  	render layout: 'auditoria_inicial'
  end

  def pesquisa_ordem_servico
	end

	def segundo_passo
		render layout: 'auditoria_inicial'
	end

	def iniciar_auditoria
		@retorno = Auditoria.cria_nova_auditoria(params[:ordem],"#{request.remote_ip}")
	end

	def ultimo_passo
		render layout: 'auditoria_inicial'
	end

end

app/controllers/modulo_entidades/administracao/home_controller.rb
#encoding: UTF-8

class ModuloEntidades::Administracao::HomeController < ApplicationController

	before_filter :valid_payment
	before_filter :verifica_se_o_usuario_eh_administrador_de_entidade


	def index
	end
	
end

app/controllers/modulo_entidades/home_controller.rb
#encoding: UTF-8

class ModuloEntidades::HomeController < ApplicationController

	before_filter :verifica_se_esta_logado


	def index
	end
	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/modulo_entidades/home_helper.rb
module ModuloEntidades::HomeHelper
end

app/views/home/bkp-index.html.erb
<div id="flash_messages">
  <% if flash[:notice] %>
    <div class="alert alert-success">
     	<button type="button" class="close" data-dismiss="alert">×</button>
    	<%= flash[:notice] %>
  	</div>
  <% end %>

  <% if flash[:error] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">×</button>
    	<%= flash[:error] %>
  	</div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">×</button>
    	<%= flash[:alert] %>
  	</div>
	<% end %>
</div>

<% unless administracao_usuario_signed_in? %>
  <% if @retorno.first %>
    <%= link_to edit_entidade_auditoria_path(@retorno.last.unidade.entidade, @retorno.last, respondendo: 1), method: :get, id: 'iniciar-auditoria' do %>
      <%= image_tag 'logo_panambra_pos_vendas.png', id: 'imgpos' %>
      <%= image_tag 'texto_pesquisa_inicial.png', id: 'txtposinicio' %>
    <% end %>
    <script type="text/javascript">
      $(function() {
        $(document).click(function() {
          $('#iniciar-auditoria').click();
        });
      });
    </script>
  <% else %>
    <%= image_tag 'logo_atendimento.png', id: 'imgpos' %>
    <div class="aguardando_pesquisa"></div>
    <script type="text/javascript">
      jQuery(function($) {
        setInterval('window.location.reload()', 5000);
      });
    </script>
  <% end %>
<% end %>

app/views/home/index.html.erb
<div id="flash_messages">
  <% if flash[:notice] %>
    <div class="alert alert-success">
     	<button type="button" class="close" data-dismiss="alert">×</button>
    	<%= flash[:notice] %>
  	</div>
  <% end %>

  <% if flash[:error] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">×</button>
    	<%= flash[:error] %>
  	</div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">×</button>
    	<%= flash[:alert] %>
  	</div>
	<% end %>
</div>

<% unless administracao_usuario_signed_in? %>
  <% if @retorno.first %>
    <%= link_to edit_entidade_auditoria_path(@retorno.last.unidade.entidade, @retorno.last, respondendo: 1), method: :get, id: 'iniciar-auditoria' do %>
      <%= image_tag 'logo_panambra_pos_vendas.png', id: 'imgpos' %>
      <%= image_tag 'texto_pesquisa_inicial.png', id: 'txtposinicio' %>
    <% end %>
    <script type="text/javascript">
      $(function() {
        $(document).click(function() {
          $('#iniciar-auditoria').click();
        });
      });
    </script>
  <% else %>
    <%= image_tag 'logo_atendimento.png', id: 'imgpos' %>
    <div class="aguardando_pesquisa"></div>
    <script type="text/javascript">
      jQuery(function($) {
        setInterval('window.location.reload()', 5000);
      });
    </script>
  <% end %>
<% end %>

app/views/home/iniciar_auditoria.js.erb
<% if @retorno.first %>
	window.location.href = '<%= edit_entidade_auditoria_path(@retorno.last.unidade.entidade, @retorno.last, ordem: params[:ordem].to_s) %>';
<% else %>
	alert('<%= @retorno.last %>');
<% end %>

app/views/home/pesquisa_ordem_servico.js.erb
<% if params[:ordem].blank? %>
	alert('Preencha o número da ordem de serviço!');
<% else %>
	<% ordem = ErpOfiAtendimento.find_by_ordem_servico(params[:ordem],"#{request.remote_ip}") %>
	<% if ordem.present? %>
		window.location.href = '<%= segundo_passo_path(ordem: ordem.first["nro_os"], placa: ordem.first["placa"]) %>';
	<% else %>
		alert('Não foi possível localizar essa Ordem de Serviço. Verifique a informação digitada!');
	<% end %>
<% end %>

app/views/home/primeiro_passo.html.erb
<%= image_tag 'logo_pos_vendas_questoes.png', class: 'logo-teclado' %>

<%= form_tag [:pesquisa_ordem_servico], class: 'form-horizontal', remote: true do %>
  <div class="ordem-servico">
    Ordem de serviço:
    <%= text_field_tag :ordem, nil, class: 'input-custom-large', readonly: true %>
  </div>
<% end %>

<div id="teclado" class="btn-group">
	<button id="botao_0" data-id="0" type="button" class="botoes-teclado btn">0</button>
	<button id="botao_1" data-id="1" type="button" class="botoes-teclado btn">1</button>
	<button id="botao_2" data-id="2" type="button" class="botoes-teclado btn">2</button>
	<button id="botao_3" data-id="3" type="button" class="botoes-teclado btn">3</button>
	<button id="botao_4" data-id="4" type="button" class="botoes-teclado btn">4</button>
	<button id="botao_5" data-id="5" type="button" class="botoes-teclado btn">5</button>
	<button id="botao_6" data-id="6" type="button" class="botoes-teclado btn">6</button>
	<button id="botao_7" data-id="7" type="button" class="botoes-teclado btn">7</button>
	<button id="botao_8" data-id="8" type="button" class="botoes-teclado btn">8</button>
	<button id="botao_9" data-id="9" type="button" class="botoes-teclado btn">9</button>
</div>

<div class="btn-group acoes">
	<button id="apagar" type="button" class="botoes-acoes btn">APAGAR</button>
	<button id="confirmar" type="button" class="botoes-acoes btn">CONFIRMAR</button>
</div>

<script type="text/javascript">
	var telaInicialUrl = '<%= url_for([:root]) %>';
	$(function() {
		$('.botoes-teclado').click(function() {
    	$('#ordem').val($('#ordem').val() + $(this).data('id'));
    	return false;
  	});
		$('#apagar').click(function() {
    	$('#ordem').val('');
    	return false;
  	});
		$('#confirmar').click(function() {
			$('form').submit();
  	});
    setInterval('verifica_uso_da_tela()', 20000);
	});
	function verifica_uso_da_tela() {
		if(!$('#ordem').val()) {
			window.location.href = telaInicialUrl;
		}
	}
</script>

app/views/home/segundo_passo.html.erb
<%= image_tag 'logo_pos_vendas_questoes.png', class: 'logo-segundo-passo' %>

<%= form_tag [:iniciar_auditoria], class: 'form-horizontal', remote: true do %>
  <div class="ordem-segundo-passo">
    Ordem de serviço:
    <%= text_field_tag :ordem, params[:ordem], class: 'input-custom-large', readonly: true %>
  </div>
  <div class="ordem-segundo-passo">
    Veículo:
    <%= text_field_tag :placa, params[:placa], class: 'input-custom-large', readonly: true %>
  </div>
<% end %>

<div class="btn-group acoes">
	<button id="responder" type="button" class="botao-grande btn">RESPONDER PESQUISA</button>
</div>

<div class="informacao">
  É rápido e fácil, são apenas 5 perguntas!
</div>

<script type="text/javascript">
	$(function() {
		$('#responder').click(function() {
			$('form').submit();
  	});
	});
</script>

app/views/home/ultimo_passo.html.erb
<%= image_tag 'tela_final.png', id: 'txtfinal' %>

<script type="text/javascript">
	$(function() {
  	setInterval("window.location.href = '<%= url_for([:root]) %>'", 10000);
	});
</script>