config/routes.rb
Template::Application.routes.draw do 

  # get '/delayed_job' => DelayedJobWeb, anchor: false

  namespace :api do
    namespace :v1 do
      post "authentications" => "authentications#create"
      post "nao_conformidades" => "nao_conformidades#index"
      post "nao_conformidade" => "nao_conformidades#show"
      post "finalizar" => "nao_conformidades#finalizar"
      post "escalonar" => "nao_conformidades#escalonar"
      post "gcm" => "gcm#show"
    end
  end

  ### PASSOS DA AUDITORIA
  match 'primeiro_passo' => 'home#primeiro_passo'
  match 'pesquisa_ordem_servico' => 'home#pesquisa_ordem_servico'
  match 'segundo_passo' => 'home#segundo_passo'
  match 'iniciar_auditoria' => 'home#iniciar_auditoria'
  match 'ultimo_passo' => 'home#ultimo_passo'

  namespace :administracao do
    devise_for :usuarios, controllers: { sessions: 'administracao/sessions',
                                         registrations: 'administracao/registrations' }
    root to: 'home#index'
    resources :entidades do 
      member do 
        get :change_status
      end
    end

    resources :administradores do 
       member do 
        get :change_status
      end
    end
  end

  match ':entidade_slug' => 'home#index', as: :entidade, module: :modulo_entidades
  scope ':entidade_slug', as: :entidade, module: :modulo_entidades do
    match 'acessar' => 'home#index'
    namespace :administracao do

      resources :unidades do
        member do
          get :change_status
        end
        collection do 
          get  :escolher_unidade
          post :acessando_unidade
          get  :sair_unidade
        end
      end

      resources :perfils do
        member do
          get :change_status
        end
      end

      resources :configuracoes

      root to: 'home#index'
    end

    resources :nao_conformidades

    resources :checklists do
      member do
        get :change_status
      end
      
      collection do 
        post :edit_questao_ajax
        post :edit_categoria_ajax
        post :nova_acao 
        post :altera_situacao_categoria
        post :altera_situacao_questao
        post :detalhe_questao
      end
      resources :questoes do 
        collection do 
          post :nova_categoria_questao
          post :nova_subcategoria_questao
          post :carrega_subcategoria
          post :nova_questao
          post :carrega_form_questao
          post :atualiza_categoria
          post :atualiza_item_verificacao
          post :cria_acao
          post :carrega_alternativa
          get :inserir_imagem
          post :upload_imagem
        end
      end
    end


    resources :auditorias do
      collection do
        get  :iniciar_pesquisa
        post :retorna_clientes
      end
    end


    resources :clientes do
      collection do
        post :autocomplete_by_nf
      end
    end


    resources :usuarios do
      member do
        get :change_status
      end
    end

    resources :relatorios do
      collection do
        get :pesquisas_respondidas
        get :pesquisas_detalhadas
        get :dashboards
        get :relatorio_ordem_servicos
      end
    end

    root to: 'home#index'
  end
  
  root to: 'home#index'
end

app/controllers/modulo_entidades/administracao/configuracoes_controller.rb
#encoding: UTF-8

class ModuloEntidades::Administracao::ConfiguracoesController < ApplicationController

	before_filter :valid_payment
	before_filter :verifica_se_o_usuario_eh_administrador_de_entidade

	def edit
		@configuracao = Configuracao.last
	end

	def update
		@configuracao = Configuracao.find(params[:id])
		if @configuracao.update_attributes(params[:configuracao])
			redirect_to [:edit, :entidade, :administracao, @configuracao], notice: 'Configuração atualizada com sucesso!'
		else
			render action: :edit
		end
	end

end

app/controllers/modulo_entidades/administracao/home_controller.rb
#encoding: UTF-8

class ModuloEntidades::Administracao::HomeController < ApplicationController

	before_filter :valid_payment
	before_filter :verifica_se_o_usuario_eh_administrador_de_entidade


	def index
	end
	
end

app/controllers/modulo_entidades/administracao/perfils_controller.rb
#encoding: UTF-8

class ModuloEntidades::Administracao::PerfilsController < ApplicationController

	before_filter :valid_payment
	before_filter :verifica_se_o_usuario_eh_administrador_de_entidade


	def index
		params[:pesquisa] ||= {}
		@perfils = Perfil.pesquisa(current_entidade.id, params[:pesquisa]).page(params[:page]).per(15)
    respond_to do |format|
      format.html
      format.json { render json: @perfils }
    end
	end

	def show
		@perfil = Perfil.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @perfil }
    end
	end

	def new
		@perfil = Perfil.new
	end

	def create
		@perfil = Perfil.new(params[:perfil])
		@perfil.entidade = current_entidade
		if @perfil.save
			redirect_to [:entidade, :administracao, @perfil], notice: 'Registro cadastrado com sucesso!'
		else
			render :new
		end
	end

	def edit
		@perfil = Perfil.find(params[:id])
	end

	def update
		@perfil = Perfil.find(params[:id])
		if @perfil.update_attributes(params[:perfil]) && params[:perfil].has_key?(:permissoes)
			redirect_to [:entidade, :administracao, @perfil], notice: 'Registro atualizado com sucesso!'
		else
			flash[:error] = 'Permissões não pode ficar em branco'
			render :edit
		end
	end

  def change_status
    @perfil = Perfil.find(params[:id])
    @perfil.change_status
    respond_to do |format|
      format.html do
        redirect_to [:entidade, :administracao, :perfils], notice: 'Situação alterada com sucesso!'
      end
      format.json do
        head :no_content
      end
    end
  end

end

app/controllers/modulo_entidades/administracao/unidades_controller.rb
#encoding: UTF-8

class ModuloEntidades::Administracao::UnidadesController < ApplicationController

	before_filter :valid_payment
	before_filter :verifica_se_o_usuario_eh_administrador_de_entidade


	def index
		params[:pesquisa] ||= {}
		@unidades = Unidade.pesquisa(current_entidade.id, params[:pesquisa]).page(params[:page]).per(15)
	end

	def show
		@unidade = Unidade.find(params[:id])
	end

	def new
		@unidade = Unidade.new
	end

	def create
		@unidade = Unidade.new(params[:unidade])
		@unidade.entidade = current_entidade
		if @unidade.save
			redirect_to [:entidade, :administracao, @unidade], notice: 'Unidade criada com sucesso!'
		else
			render :new
		end
	end

	def edit
		@unidade = Unidade.find(params[:id])
	end

	def update
		@unidade = Unidade.find(params[:id])
		if @unidade.update_attributes(params[:unidade])
			redirect_to [:entidade, :administracao, @unidade], notice: 'Unidade atualizada com sucesso!'
		else
			render :edit
		end
	end

  def change_status
    @unidade = Unidade.find(params[:id])
    @unidade.change_status
    respond_to do |format|
      format.html do
        redirect_to [:entidade, :administracao, :unidades], notice: 'Status alterado com sucesso!'
      end
      format.json do
        head :no_content
      end
    end
  end

	def escolher_unidade
	end

	def sair_unidade
		session[:unidade] = nil
		redirect_to [:escolher_unidade, :entidade, :administracao, :unidades]
	end

	def acessando_unidade
		session[:unidade] = Unidade.find_by_id(params[:unidade_id])
		if session[:unidade].blank?
			flash[:error] = 'Erro! Você deve selecionar uma unidade!'
			redirect_to root_path
		else
			redirect_to [:entidade, :root]
		end
	end

end

app/controllers/modulo_entidades/auditorias_controller.rb
#encoding: UTF-8

class ModuloEntidades::AuditoriasController < ApplicationController

	before_filter :valid_payment
	before_filter :verifica_se_esta_logado, except: [:edit, :update, :retorna_clientes]
	before_filter :verifica_se_o_usuario_escolheu_uma_unidade, except: [:edit, :update, :retorna_clientes]


	def index
		params[:pesquisa] ||= {}
		@auditorias = Auditoria.pesquisa(current_unidade.id, params[:pesquisa])
													 .page(params[:page])
													 .per(15)
	end

	def show
		@auditoria = Auditoria.find(params[:id])
	end

	def new
		@auditoria = Auditoria.new
	end

	def create
		@auditoria = Auditoria.new
		
		
		conf = request.remote_ip
		acurrent_unidade = Unidade.first
	if conf == "localhost" || conf == "192.168.202.90" || conf == "127.0.0.1"
  	 acurrent_unidade = Unidade.first
	elsif conf == "192.168.170.89"
	 acurrent_unidade = Unidade.find 2
	elsif conf == "211.0.144.90"
	 acurrent_unidade = Unidade.find 3
	elsif conf == "192.168.130.90"
	 acurrent_unidade = Unidade.find 4 
	elsif conf == "211.0.137.90"
	  acurrent_unidade = Unidade.find 5
	end
		
		@auditoria.unidade = acurrent_unidade
		@auditoria.checklist = current_unidade.retorna_checklist_ativo
		
		

		if params[:opcao].to_i == Auditoria::SIM
			erp_cliente = ErpFatCliente.where(cliente: params[:codigo_cliente]).first rescue nil
			if erp_cliente.present?
				params[:cliente] = { codigo: params[:codigo_cliente], nome: erp_cliente.nome, cpf_cnpj: nil }
				@auditoria.cliente = Cliente.cria_ou_recupera_cliente_comum(current_unidade.id, params[:cliente])
			end
		elsif params[:opcao].to_i == Auditoria::ESPONTANEA
			@auditoria.cliente = Cliente.cria_ou_recupera_cliente_espontaneo(current_unidade.id)
		end

		if @auditoria.save
			if current_user.perfil_id.blank?
				redirect_to [:entidade, :auditorias], notice: 'Auditoria liberada com sucesso!'
			else
				redirect_to [:new, :entidade, :auditoria], notice: 'Auditoria liberada com sucesso!'
			end
		else
			render :new
		end
	end

	def edit
		@auditoria = Auditoria.find(params[:id])
		my_logger ||= Logger.new("#{Rails.root}/log/numero_de_ordem273148912378.log")
		my_logger.info("#{request.remote_ip}")
		render layout: 'auditoria_inicial'
		
	end

	def update
		@auditoria = Auditoria.find(params[:id])
		#@retorno 	 = @auditoria.salvar_respostas(params,request.url.split("//").last.split("/").first.split(":").first)
		@retorno 	 = @auditoria.salvar_respostas(params,request.remote_ip)
	end

	def iniciar_pesquisa
		@retorno = Auditoria.retorna_auditoria_para_ser_respondida(request.remote_ip)
		my_logger ||= Logger.new("#{Rails.root}/log/numero_de_ordem.log")
		my_logger.info("#{request.url}")
	end

	def retorna_clientes
    configuracao = Configuracao.first
    @clientes 	 = []
    @clientes_ids = ErpFatFrenteCaixa.where(revenda: configuracao.revenda)
    														 		 .where(situacao: 'P')
    														 		 .where(caixa: configuracao.caixas.split(', '))
    														 		 .where(origem: configuracao.origem)
    														 		 .limit(10)
    														 		 .pluck(:cliente_emissao_nf)
    														 		 .uniq
    @clientes = ErpFatCliente.where(cliente: @clientes_ids).order(:nome) rescue nil if @clientes_ids.present?
    # @clientes = Cliente.where(unidade_id: configuracao.caixas.split(', '))
  end

end

app/controllers/modulo_entidades/checklists_controller.rb
#encoding: UTF-8

class ModuloEntidades::ChecklistsController < ApplicationController

	before_filter :valid_payment
	before_filter :verifica_se_esta_logado
	before_filter :verifica_se_o_usuario_escolheu_uma_unidade


	def index
		params[:pesquisa] ||= {}
		@checklists = Checklist.pesquisa(current_unidade.id, params[:pesquisa])
													 .page(params[:page])
													 .per(15)
	end

	def show
		@checklist = Checklist.find(params[:id])
		@item_checklists = @checklist.carrega_categorias
	end

	def new
		@checklist = Checklist.new
	end

	def create
		@checklist = Checklist.new(params[:checklist])
		@checklist.unidade = current_unidade
		if @checklist.save
			redirect_to [:entidade, @checklist], notice: 'Checklist criado com sucesso!'
		else
			render :new
		end
	end

	def edit
		@checklist = Checklist.find(params[:id])
	end

	def edit_categoria_ajax
		@item_checklist = ItemChecklist.find(params[:id])
		@checklist = @item_checklist.checklist
		respond_to do |format|
			format.js
		end
	end

	def edit_questao_ajax
		@item_verificacao  = ItemVerificacao.find(params[:id])
		@item_checklist = @item_verificacao.item_checklist
		@checklist = @item_checklist.checklist
		respond_to do |format|
			format.js
		end
	end

	def detalhe_questao
		@item_verificacao  = ItemVerificacao.find(params[:id])
		@item_checklist = @item_verificacao.item_checklist
		@checklist = @item_checklist.checklist
		respond_to do |format|
			format.js
		end
	end

	def nova_acao
		@item_verificacao  = ItemVerificacao.find(params[:id])
		@alternativas = @item_verificacao.alternativas
		@acoes = @item_verificacao.acoes
		@item_checklist = @item_verificacao.item_checklist
		@checklist = @item_checklist.checklist
		respond_to do |format|
			format.js
		end
	end
	
	def update
		@checklist = Checklist.find(params[:id])
		@checklist.unidade = current_unidade
		if @checklist.update_attributes(params[:checklist])
			redirect_to [:entidade, @checklist], notice: 'Checklist atualizado com sucesso!'
		else
			render :edit
		end
	end

	def altera_situacao_categoria
		@item_checklist = ItemChecklist.find(params[:id])
		if @item_checklist.situacao == ItemChecklist::ATIVO 
			@item_checklist.situacao = ItemChecklist::INATIVO
		else
			@item_checklist.situacao = ItemChecklist::ATIVO
		end
		@item_checklist.save
		render js: "alert('Situação alterada com sucesso!');window.location.reload();"
	end

	def altera_situacao_questao
		@item_verificacao = ItemVerificacao.find(params[:id])
		if @item_verificacao.situacao == ItemVerificacao::ATIVO 
			@item_verificacao.situacao = ItemVerificacao::INATIVO
		else
			@item_verificacao.situacao = ItemVerificacao::ATIVO
		end
		@item_verificacao.save
		render js: "alert('Situação alterada com sucesso!');window.location.reload();"
	end

  def change_status
    @checklist = Checklist.find(params[:id])
    @checklist.change_status
    respond_to do |format|
      format.html do
        redirect_to [:entidade, :checklists], notice: 'Status alterado com sucesso!'
      end
      format.json do
        head :no_content
      end
    end
  end

end

app/controllers/modulo_entidades/clientes_controller.rb
#encoding: UTF-8

class ModuloEntidades::ClientesController < ApplicationController

  before_filter :valid_payment
	before_filter :verifica_se_esta_logado
	before_filter :verifica_se_o_usuario_escolheu_uma_unidade


	def index
		params[:pesquisa] ||= {}
		@clientes = Cliente.pesquisa(current_unidade.id, params[:pesquisa])
											 .page(params[:page])
											 .per(15)
	end

  def autocomplete_by_nf
    @retorno     = []
    @nota_fiscal = ErpNotaFiscal.where('EMPRESA = ?', 1)
                                .where('REVENDA = ?', 1)
                                .where('TIPO_TRANSACAO IN(?)', ['V21', 'G21', '021', 'U21'])
                                .where('NUMERO_NOTA_FISCAL = ?', params[:pesquisa])
                                .first rescue nil

    @clientes = ErpCliente.where('CLIENTE = ?', @nota_fiscal.cliente) rescue nil if @nota_fiscal.present?
    if @clientes.present?
      @clientes.each do |objeto|
        @retorno << { label: "(#{@nota_fiscal.numero_nota_fiscal}) #{objeto.cliente} - #{objeto.nome}",
                      value: "(#{@nota_fiscal.numero_nota_fiscal}) #{objeto.cliente} - #{objeto.nome}",
                      id: objeto.id,
                      # cpf_cnpj: objeto.cpf_cnpj,
                      cpf_cnpj: nil,
                      codigo: objeto.cliente,
                      nome: objeto.nome
                    }
      end
    else
      @retorno << { label: 'Nota fiscal não encontrada!', value: 'Nota fiscal não encontrada!', id: nil }
    end
    respond_to do |format|  
      format.json { render json: @retorno.to_json }
    end
  end

end

app/controllers/modulo_entidades/home_controller.rb
#encoding: UTF-8

class ModuloEntidades::HomeController < ApplicationController

	before_filter :verifica_se_esta_logado


	def index
	end
	
end

app/controllers/modulo_entidades/respostas_controller.rb
#encoding: UTF-8

class ModuloEntidades::RespostasController < ApplicationController

	before_filter :valid_payment
	before_filter :verifica_se_esta_logado
	before_filter :verifica_se_o_usuario_escolheu_uma_unidade


	def index
	end


end

app/helpers/modulo_entidades/administracao/configuracoes_helper.rb
module ModuloEntidades::Administracao::ConfiguracoesHelper
end

app/helpers/modulo_entidades/administracao/perfils_helper.rb
module ModuloEntidades::Administracao::PerfilsHelper
end

app/helpers/modulo_entidades/administracao/unidades_helper.rb
module ModuloEntidades::Administracao::UnidadesHelper
end

app/helpers/modulo_entidades/administracao/usuarios_helper.rb
module ModuloEntidades::Administracao::UsuariosHelper
end

app/helpers/modulo_entidades/auditorias_helper.rb
module ModuloEntidades::AuditoriasHelper

	def monta_checklist_de_auditoria(item_verificacao, index)
		if item_verificacao.present?
			if item_verificacao.tipo == ItemVerificacao::SIM_NAO
	    	render('sim_nao', item_verificacao: item_verificacao, numero: index)
		 	elsif item_verificacao.tipo == ItemVerificacao::SIM_NAO_TEXTO
				render('sim_nao_texto', item_verificacao: item_verificacao, numero: index)
		 	elsif item_verificacao.tipo == ItemVerificacao::TEXTO
				render('texto', item_verificacao: item_verificacao, numero: index)
			elsif item_verificacao.tipo == ItemVerificacao::ESCALA
				render('escala', item_verificacao: item_verificacao, numero: index)
	   	end
	  end
	end

end

app/helpers/modulo_entidades/checklists_helper.rb
module ModuloEntidades::ChecklistsHelper
end

app/views/modulo_entidades/questoes/_alternativa.html.erb
<table>
	<thead>
		<tr>
			<th>Opção</th>
			<th>Nota</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				Sim
				<%= hidden_field_tag 'item_verificacao[alternativas_attributes][1][titulo]', 'Sim' %>
			</td>
			<td>
				<%= text_field_tag 'item_verificacao[alternativas_attributes][1][peso]' %>
			</td>
		</tr>
		<tr>
			<td>
				Não
				<%= hidden_field_tag 'item_verificacao[alternativas_attributes][2][titulo]', 'Não' %>
			</td>
			<td>
				<%= text_field_tag 'item_verificacao[alternativas_attributes][2][peso]' %>
			</td>
		</tr>
	</tbody>
</table>

app/views/modulo_entidades/questoes/_alternativa_escala.html.erb
<% index = Digest::SHA1.hexdigest([Time.now, rand].join)[0..10] %>
<% p index %>
<table>
	<thead>
		<tr>
			<th>Título</th>
			<th>Nota</th>
			<th></th>

		</tr>
	</thead>
	<tbody>
		<tr id="tr_<%=index%>">
			<td>
				<%= text_field_tag "item_verificacao[alternativas_attributes][#{index}][titulo]" %>
			</td>
			<td>
				<%= text_field_tag "item_verificacao[alternativas_attributes][#{index}][peso]" %>
			</td>
			<td>
				<%=link_to "Excluir","#",{:class=>"link_excluir"}%>
			</td>
		</tr>
	</tbody>
</table>

<script type="text/javascript">
	$('.link_excluir').click(function(){
		$(this).closest("table").remove();
		return false;
	});
</script>

app/views/modulo_entidades/questoes/_form_questoes.html.erb
<h2>Nova Questão</h2>
<%= form_tag [:nova_questao, :entidade, @checklist, :questoes], method: :post, remote: true do %>	
	<div class="field control-group" style="float:left;">
		<label class="control-label">Tipo</label>
			<div class="controls">
			  <%= select_tag 'item_verificacao[tipo]', options_for_select([''] + ItemVerificacao.retorna_tipo_para_select) %>
			</div>
		<label class="control-label">Título</label>
		<div class="controls">
			<%= text_field_tag 'item_verificacao[titulo]', nil, class: 'input-large', maxlength: 255 %>
			<%= hidden_field_tag 'item_verificacao[item_checklist_id]', @item_checklist.id %>
		</div>
		<label class="control-label">De-Para</label>
		<div class="controls">
			<%= text_field_tag 'item_verificacao[de_para]', nil, class: 'input-small numeric', maxlength: 10 %>
			<%= submit_tag 'Criar Questão', class: 'btn btn-inverse', data: { disable_with: 'Criando...' } %>
		</div>
	</div>
	<br />
	<div id="link_add_alternativa" style="display:none">
		<%=link_to "Adicionar Alternativa","#",{:id=>"add_alternativa"} %>
	</div>
  	<div id="alternativas" style="padding:30px"></div>
<% end %>

<script type="text/javascript">
	initializeNumericMask();
	$('#item_verificacao_tipo').live('change', function() {
		$('#alternativas').html('');
		var opcao = $("#item_verificacao_tipo").val();
		if(opcao == 2 || opcao == 1) {
			$("#link_add_alternativa").hide();
			$('#alternativas').html("<%= escape_javascript(render('alternativa')) %>");
		}else if (opcao == 4)
		{
			$("#link_add_alternativa").show();
		} 
		else {
			$("#link_add_alternativa").hide();
			$("#alternativas").html('');
		}
	});

	$("#link_add_alternativa").click(function(){

		$.ajax({
      url: '<%= url_for([:carrega_alternativa, :entidade, @checklist, :questoes]) %>',
      type: 'POST',
      data: { categoria_questao_id: $("#categoria_questao_id").val()  },
      dataType: 'script'
    });
		return false;
	});
</script>

app/views/modulo_entidades/questoes/_form_subcategoria.html.erb
<%=form_tag [:nova_subcategoria_questao,:entidade,@checklist,:questoes], :method=>"post",:remote=>true do %>	
	<div class="field control-group">
		<label class="control-label">Subcategoria</label>
			<div class="controls">
			    <%=select_tag 'item_checklist[item_checklist_id]',options_for_select(ItemChecklist.retorna_subcategoria_para_select(current_unidade.id,@item_checklist.id)), :id=>"subcategoria_questao_id" %> 
			</div>
		<div class="controls">
			 <label>ou crie uma nova</label>
			<%= text_field_tag 'item_checklist[nome]',nil, class: 'input-large', :id=>"subcategoria_nome",maxlength: 255 %>
			<%= hidden_field_tag 'item_checklist[item_checklist_id]',@item_checklist.id%>
		</div>
		<label class="control-label">Peso</label>
		<div class="controls">
			<%= text_field_tag 'item_checklist[peso]',nil, class: 'input-large',:id=>"subcategoria_peso", maxlength: 255 %>
			<%= submit_tag 'Criar Subcategoria', class: 'btn btn-inverse', data: { disable_with: 'Criando...' } %>
		</div>
	</div>
<%end%>

app/views/modulo_entidades/questoes/atualiza_categoria.js.erb
<% if @item_checklist.update_attributes(params[:item_checklist]) %>
   alert('Categoria atualizada com sucesso!');
   window.location.reload();
<% else %>
	alert('<%= @item_checklist.errors.full_messages.collect{|mensagem| "* #{mensagem}"}.join("\\n") %>');
<% end %>

app/views/modulo_entidades/questoes/atualiza_item_verificacao.js.erb
<% if @item_verificacao.update_attributes(params[:item_verificacao]) %>
   alert('Questão atualizada com sucesso!');
   window.location.reload();
<% else %>
	alert('<%= @item_verificacao.errors.full_messages.collect{|mensagem| "* #{mensagem}"}.join("\\n") %>');
<% end %>

app/views/modulo_entidades/questoes/carrega_form_questao.js.erb
$('#form_questao').html("<%= escape_javascript(render('form_questoes')) %>");

app/views/modulo_entidades/questoes/carrega_subcategoria.js.erb
$('#subcategoria_questao').html("<%= escape_javascript(render('form_subcategoria')) %>");

app/views/modulo_entidades/questoes/cria_acao.js.erb
<% if @acao.save %>
	alert('Ação criada com sucesso!');
	window.location.reload();
<% else %>
	alert('<%= @acao.errors.full_messages.collect{|mensagem| "* #{mensagem}"}.join("\\n") %>');
<% end %>

app/views/modulo_entidades/questoes/index.html.erb
<div class="titulo-pagina">
  Questões »
</div>
<br />

<% if @questoes.any? %>
  <table class="table table-striped table-condensed">
    <thead>
      <tr>
        <th>Titulo</th>
        <th>Tipo</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @questoes.each do |q| %>
        <tr>
          <td><%= q.titulo %></td>
          <td><%= q.tipo_verbose %></td>
          <td></td>
          <%if q.tipo == 4%>
          <td><%=link_to "Inserir Imagens",inserir_imagem_entidade_checklist_questoes_path(@checklist.unidade.entidade,@checklist,:questao_id=>q.id) %>
            
            <%else%>
            <td>Não permitido</td>
            <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <strong>Sem registros para exibir!</strong>
<% end %>

<br />
<%= link_to 'Voltar', [:entidade, @checklist], class: 'btn' %>

app/views/modulo_entidades/questoes/inserir_imagem.html.erb
<%= form_tag [:upload_imagem,:entidade, @checklist, :questoes], :multipart => true do  %>
  
  
  <div class="field control-group">
    <span>Alternativa</span>
    <div class="controls">
      <%= select_tag 'item_verificacao[alternativa_id]',options_for_select(@alternativas.collect{|x| [x.titulo,x.id]})%>
    </div>
  </div>

  <div class="field control-group">
    <span>Arquivo</span>
    <div class="controls">
      <%= file_field_tag 'arquivo' %>
    </div>
  </div>

  <div class="actions form-actions">
    <%= submit_tag 'Salvar', class: 'btn btn-inverse', data: { disable_with: 'Salvando...' } %>
    
  </div>

 <%end%>


 <h3>Alternativas</h3>
 <br />
 <table>
 		<thead>
 			<tr>
 				<td>Alternativa</td>
 				<td>Imagem</td>
 			</tr>
 		</thead>
 		<tbody>
 			<%@alternativas.each do |alternativa| %>
 				<tr>
 					<td><%=alternativa.titulo%></td>
 					<td><%= image_tag alternativa.arquivo%></td>
 				</tr>
 			<%end%>
 		</tbody>

 </table>

app/views/modulo_entidades/questoes/nova_categoria_questao.js.erb
<% if @item_checklist.save %>
	$('#subcategoria_questao').html("<%= escape_javascript(render('form_subcategoria')) %>");
<% else %>
	alert('<%= @item_checklist.errors.full_messages.collect{|mensagem| "* #{mensagem}"}.join("\\n") %>');
<% end %>

app/views/modulo_entidades/questoes/nova_questao.js.erb
<% if @item_verificacao.save %>
	alert('Questão criada com sucesso!');
	window.location.reload();
<% else %>
	alert('<%= @item_verificacao.errors.full_messages.collect{|mensagem| "* #{mensagem}"}.join("\\n") %>');
<% end %>

app/views/modulo_entidades/questoes/nova_subcategoria_questao.js.erb
<% if @item_checklist.save %>
	$('#form_questao').html("<%= escape_javascript(render('form_questoes')) %>");
<% else %>
	alert('<%= @item_checklist.errors.full_messages.collect{|mensagem| "* #{mensagem}"}.join("\\n") %>');
<% end %>